"""Add division and course to RoomBooking

Revision ID: 0f97a0ff9e61
Revises: dfd4d6286793
Create Date: 2026-04-30 10:34:42.268653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0f97a0ff9e61'
down_revision = 'dfd4d6286793'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('division', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('course', sa.String(length=100), nullable=True))

    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('timetables', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=postgresql.TIME(),
               nullable=True)

    with op.batch_alter_table('room_bookings', schema=None) as batch_op:
        batch_op.drop_column('course')
        batch_op.drop_column('division')

    # ### end Alembic commands ###
